export const TAILOR_ORDER_CREATE_REQUEST = 'TAILOR_ORDER_CREATE_REQUEST';
export const TAILOR_ORDER_CREATE_SUCCESS = 'TAILOR_ORDER_CREATE_SUCCESS';
export const TAILOR_ORDER_CREATE_FAIL = 'TAILOR_ORDER_CREATE_FAIL';
export const TAILOR_ORDER_CREATE_RESET = 'TAILOR_ORDER_CREATE_RESET';

export const TAILOR_ORDER_PAY_REQUEST = 'TAILOR_ORDER_PAY_REQUEST';
export const TAILOR_ORDER_PAY_SUCCESS = 'TAILOR_ORDER_PAY_SUCCESS';
export const TAILOR_ORDER_PAY_FAIL = 'TAILOR_ORDER_PAY_FAIL';
export const TAILOR_ORDER_PAY_RESET = 'TAILOR_ORDER_PAY_RESET';

export const TAILOR_ORDER_DETAILS_REQUEST = 'TAILOR_ORDER_DETAILS_REQUEST';
export const TAILOR_ORDER_DETAILS_SUCCESS = 'TAILOR_ORDER_DETAILS_SUCCESS';
export const TAILOR_ORDER_DETAILS_FAIL = 'TAILOR_ORDER_DETAILS_FAIL';

export const TAILOR_ORDER_MINE_LIST_REQUEST = 'TAILOR_ORDER_MINE_LIST_REQUEST';
export const TAILOR_ORDER_MINE_LIST_SUCCESS = 'TAILOR_ORDER_MINE_LIST_SUCCESS';
export const TAILOR_ORDER_MINE_LIST_FAIL = 'TAILOR_ORDER_MINE_LIST_FAIL';

export const TAILOR_ORDER_LIST_REQUEST = 'TAILOR_ORDER_LIST_REQUEST';
export const TAILOR_ORDER_LIST_SUCCESS = 'TAILOR_ORDER_LIST_SUCCESS';
export const TAILOR_ORDER_LIST_FAIL = 'TAILOR_ORDER_LIST_FAIL';

export const TAILOR_ORDER_DELETE_REQUEST = 'TAILOR_ORDER_DELETE_REQUEST';
export const TAILOR_ORDER_DELETE_SUCCESS = 'TAILOR_ORDER_DELETE_SUCCESS';
export const TAILOR_ORDER_DELETE_FAIL = 'TAILOR_ORDER_DELETE_FAIL';
export const TAILOR_ORDER_DELETE_RESET = 'TAILOR_ORDER_DELETE_RESET';

export const TAILOR_ORDER_DELIVER_REQUEST = 'TAILOR_ORDER_DELIVER_REQUEST';
export const TAILOR_ORDER_DELIVER_SUCCESS = 'TAILOR_ORDER_DELIVER_SUCCESS';
export const TAILOR_ORDER_DELIVER_FAIL = 'TAILOR_ORDER_DELIVER_FAIL';
export const TAILOR_ORDER_DELIVER_RESET = 'TAILOR_ORDER_DELIVER_RESET';