export const TAILORMADE_ADD_ITEM = 'TAILORMADE_ADD_ITEM';
export const TAILORMADE_REMOVE_ITEM = 'TAILORMADE_REMOVE_ITEM';
export const TAILORMADE_SAVE_SHIPPING_ADDRESS = 'TAILORMADE_SAVE_SHIPPING_ADDRESS';
export const TAILORMADE_SAVE_PAYMENT_METHOD = 'TAILORMADE_SAVE_PAYMENT_METHOD';
export const TAILORMADE_EMPTY = 'TAILORMADE_EMPTY';