export const TAILORMADE_LIST_REQUEST = 'TAILORMADE_LIST_REQUEST';
export const TAILORMADE_LIST_SUCCESS = 'TAILORMADE_LIST_SUCCESS';
export const TAILORMADE_LIST_FAIL = 'TAILORMADE_LIST_FAIL';

export const TAILORMADE_DETAILS_REQUEST = 'TAILORMADE_DETAILS_REQUEST';
export const TAILORMADE_DETAILS_SUCCESS = 'TAILORMADE_DETAILS_SUCCESS';
export const TAILORMADE_DETAILS_FAIL = 'TAILORMADE_DETAILS_FAIL';

export const TAILORMADE_CREATE_REQUEST = 'TAILORMADE_CREATE_REQUEST';
export const TAILORMADE_CREATE_SUCCESS = 'TAILORMADE_CREATE_SUCCESS';
export const TAILORMADE_CREATE_FAIL = 'TAILORMADE_CREATE_FAIL';
export const TAILORMADE_CREATE_RESET = 'TAILORMADE_CREATE_RESET';

export const TAILORMADE_DELETE_REQUEST = 'TAILORMADE_DELETE_REQUEST';
export const TAILORMADE_DELETE_SUCCESS = 'TAILORMADE_DELETE_SUCCESS';
export const TAILORMADE_DELETE_FAIL = 'TAILORMADE_DELETE_FAIL';
export const TAILORMADE_DELETE_RESET = 'TAILORMADE_DELETE_RESET';

export const TAILORMADE_UPDATE_RESET = 'TAILORMADE_UPDATE_RESET';
export const TAILORMADE_UPDATE_SUCCESS = 'TAILORMADE_UPDATE_SUCCESS';
export const TAILORMADE_UPDATE_REQUEST = 'TAILORMADE_UPDATE_REQUEST';
export const TAILORMADE_UPDATE_FAIL = 'TAILORMADE_UPDATE_FAIL';